### ISSUE TITLE
Project link https://mental-health.netlify.app/ is not found

### ISSUE THREAD

**Issue by alphaolomi** [ghmeec/Mental-Health-Therapy-2020#16]
![20201024_183659](https://user-images.githubusercontent.com/10551599/97085732-f1ba8300-1627-11eb-9c01-4f7241f6e02c.jpg)

**Comment by ghmeec** [comment]
Working to fix it... thanks for reporting

**Comment by alphaolomi** [comment]
Check it works 🚀
